/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar1: [{type: 'autogenerated', dirName: '.'}],

  /*mySidebar: [
    'intro',
    {
      type: 'category',
      label: 'Tutorials',
      items: [
        {
          type: 'autogenerated',
          dirName: 'side1', // Generate sidebar slice from docs/tutorials/easy
        },
      ],
    },
    {
      type: 'autogenerated',
      dirName: 'side2', // Generate sidebar slice from docs/api
    },
    {
      type: 'category',
      label: 'Community',
      items: ['test'],

    },
  ]*/
  // But you can create a sidebar manually
/*
  tutorialSidebar2: [
    {
      type: 'category',
      label: 'Tutorial_2',
      items: ['intro'],
    },
  ],
*/
};

module.exports = sidebars;
